predefined_values = {
    1: {
        "file_name": "2_Паспорт__Программа_s58wkyP.docx",
        "prog_name": "разработка приложение для мобильный устройство",
        "hours_total": 72,
        "hours_prac": 50,
        "online": True,
        "difficulty": "базовый",
        "min_listeners": 100,
        "max_listeners": 120,
        "taxonomies": [
            "разработка алгоритм",
            "среда программирование",
            "r",
            "android",
            "база данные",
            "методология разработка",
            "xml",
            "java",
            "работа с база данные",
            "структура данные",
            "linux",
        ],
        "taxonomy": 0.07748830995323983,
        "expected_taxonomy_match": 0.7272727272727273,
        "positive_reviews": 6,
        "neutral_reviews": 30,
        "negative_reviews": 2,
    },
    2: {
        "file_name": "FIN_ОП_Кибербезопасность_UBpe3f7.docx",
        "prog_name": "метод искусственный интеллект в кибербезопасность",
        "hours_total": 72,
        "hours_prac": 50,
        "online": True,
        "difficulty": "базовый",
        "min_listeners": 100,
        "max_listeners": 100,
        "taxonomies": [
            "ml",
            "precision",
            "метод исследование",
            "метод машинный обучение",
            "логистический регрессия",
            "python",
            "отбор признак",
            "auc",
            "статистический анализ",
            "интеллектуальный анализ данные",
            "линейный регрессия",
        ],
        "taxonomy": 0.134936539746159,
        "expected_taxonomy_match": 0.36363636363636365,
        "positive_reviews": 6,
        "neutral_reviews": 20,
        "negative_reviews": 1,
    },
    3: {
        "file_name": "Аддитивные_технологии.docx",
        "prog_name": "производство изделие с " "использование аддитивный " "технология",
        "hours_total": 72,
        "hours_prac": 61,
        "online": True,
        "difficulty": "базовый продвинуть",
        "min_listeners": 5,
        "max_listeners": 100,
        "taxonomies": ["проектирование", "stl", "прототипирование"],
        "taxonomy": 0.022857142857142857,
        "expected_taxonomy_match": 0.3333333333333333,
        "positive_reviews": 3,
        "neutral_reviews": 14,
        "negative_reviews": 1,
    },
    4: {
        "file_name": "Версия_2_sjFHknF.docx",
        "prog_name": "искусственный интеллект и его приложение",
        "hours_total": 72,
        "hours_prac": 68,
        "online": True,
        "difficulty": "базовый",
        "min_listeners": 10,
        "max_listeners": 20,
        "taxonomies": [
            "pandas",
            "метод опорный вектор",
            "линейный регрессия",
            "matplotlib",
            "keras",
            "оценка качество модель",
            "логистический регрессия",
            "auc",
            "интеллектуальный анализ данные",
            "django",
            "метод исследование",
            "визуализация данные",
            "apache spark",
            "accuracy",
            "отбор признак",
            "градиентный бустинг",
            "обучение нейронный сеть",
            "precision",
            "spark",
            "эксперимент",
        ],
        "taxonomy": 0.12491649966599865,
        "expected_taxonomy_match": 0.4,
        "positive_reviews": 7,
        "neutral_reviews": 29,
        "negative_reviews": 8,
    },
    5: {
        "file_name": "ИТМАБД_72ч_Паспорт_программы_101020_4AMuCQH.docx",
        "prog_name": "инструмент и технология моделирование и анализ больший данные",
        "hours_total": 72,
        "hours_prac": 54,
        "online": True,
        "difficulty": "базовый",
        "min_listeners": 15,
        "max_listeners": 300,
        "taxonomies": [
            "ml",
            "классификация данные",
            "анализ текст",
            "сегментация",
            "python",
            "windows",
            "разработка модель машинный обучение",
            "анализ больший данные",
            "оценка качество модель",
            "rapidminer",
            "tensorflow",
            "tableau",
            "интеллектуальный анализ данные",
            "olap",
            "r",
            "android",
            "визуализация данные",
            "ios",
            "k-means",
            "spark",
            "база данные",
            "hive",
            "структура данные",
            "xgboost",
        ],
        "taxonomy": 0.23313293253173017,
        "expected_taxonomy_match": 0.625,
        "positive_reviews": 132,
        "neutral_reviews": 340,
        "negative_reviews": 32,
    },
}
